### ISSUE TITLE
iVAF Calculation 

### ISSUE THREAD

**Issue by AnimaTardeb** [ababaian/Crown#1]
Hello, 
First nice work :) 
Seconde I am a lil lost in how you calculated the iVCF 
can you please indicate the parameters that you used? because I am not able to get the same results?
Thanks for your help

**Comment by ababaian** [comment]
intra-individual variant allele frequency, which experiment are you specifically referring to?

From the [pre-print](https://www.biorxiv.org/content/early/2017/03/21/118760):
> " For the interrogated variant positions, intra-
> individual reference allele frequency was calculated by the number of reference 
> genotype read coverage, divided by the total read coverage used in genotyping. 
> The inverse of the reference allele frequency was defined as the intra-individual 
> variant allele frequency (iVAF). I calculated iVAF in this way to account for 
> positions with multiple variant alleles and to measure iVAF in genomes where  
> variant alleles may not have been called by the software, yet variant reads were 
> present. The mean intra-individual variant allele frequency is simply the average 
> value of iVAF for each genome in which a variant was present."

**Comment by AnimaTardeb** [comment]
Tanks  for you answer
I want to see the VAF, and I used to calculate it from VCF 4.1  that
contains different annotation. AO and DP.

From this part of your article article I recalculated the iVAF from the VCF
file u provided and I was not able to get the value of 0.52 for the allele
at 1000777 (first allele in the table )
I used the AD/DP   and inverted Ann my values with no success( i used also
other annotation that I know they must be incorrect).

Thanks

**Comment by ababaian** [comment]
Sorry, I'm not sure which table or which exact VCF file you're referring to, if you can link them here I can better help.

iVAF will be different in every person so the value of 0.52 might refer to one person and you're looking at another.

**Comment by AnimaTardeb** [comment]
Hello, Ok. 
I want to calculate (re calculate)  the VAF for the data you provided in the article. 
So, I downloaded the g.VCF file you provided here: [http://rrna.ca/data/100genomes.hgr1.g.vcf.gz]()
and I started calculating the VAF, iVAF, pVAF according to the discerption page 13 lines 245, 250 and 255. 

> iVAF will be different in every person so the value of 0.52 might refer to one person and you're looking at another.

Yes, you are right, I found the sample/person that has the iVAF =0.52. 

To make it short, my stupid question is,  how did you calculate this value ? what was the formula used (I know, it is described,  I can read it from the article, but ...) 
for my calculation: 
- iVAF =AD/DP (Allele depth / read depth) 
- pVAF= mean(iVAF) 
- sd(pVAF)= sd(iVAF)

Is this correct ?

Thanks a lot for your time

**Comment by ababaian** [comment]
OK, from `107genomes.hgr1.g.vcf` file, the line for the allele you mentioned is: 

```
chr13	1000777	.	CGG	C,CGGG,CGGGG	382290.33	.	AC=21,16,71;AF=0.111,0.084,0.374;AN=190;BaseQRankSum=-1.592;ClippingRankSum=0.017;DP=35893;ExcessHet=93.7401;FS=1.132;InbreedingCoeff=-0.5675;MLEAC=14,16,69;MLEAF=0.074,0.084,0.363;MQ=43.14;MQRankSum=-9.988;QD=13.24;ReadPosRankSum=-1.788;SOR=0.620	GT:AD:DP:GQ:PL	./.	0/3:279,1,105,99:484:73:3223,4975,24658,73,9624,7861,0,11693,5880,10241	./.	...
```

The `INFO` columns contain AD/GP so for the first two people it's:
```
FORMAT	HG00128	HG00139
GT:AD:DP:GQ:PL	./.	0/3:279,1,105,99:484:73:3223,4975,24658,73,9624,7861,0,11693,5880,10241
```

The first person `HG00128` there is no information for this allele (i.e. no variant detected thus `./.`).

The second person `HG00139` has an AD of  `279,1,105,99` and DP of `484`
```
279,1,105,99:484
```
So for the reference allele (RAF) the coverage is `279` / `484`. The variant allele frequency is `(1 + 105 + 99) / 484`
```
# Reference Allele Frequency
iRAF = AD_reference / GD
# ( 0.5764 )

iVAF = 1 - iRAF    # Inverse of 

# Variant Allle Frequency
iVAF = AD_nonreferences / GD
```

And yes you are correct about population variant allele frequency calculation. I hope that clarifies the calculation. I'll make sure to add formulas to the manuscript when I update it.

**Comment by AnimaTardeb** [comment]
Oh, thanks a lot, ok, it is exactly how I did it.

I had a good discussion with my colleague about this" inverse of ". for him and me at the beginning: inverse of X is 1/X and by comparing the results I obtained, I understood that your inverse is 1-X (because you are considering the reference not the allele to calculate the  allele frequency).
so, again, thanks a lot for your time and answers 

you can close the issue
